In [1]:
import cv2
import numpy as np

### Image Operations

In [2]:
img= cv2.imread('watch.jpg', 1)

roi=img[1000,800]
print(roi)
roi= img[200:350, 200:350]
print(roi)

img[200:350, 200:350]=[255,255,255]
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[ 92 101 151]
[[[102 132 213]
  [ 98 128 209]
  [ 95 125 208]
  ...
  [122 151 220]
  [ 95 123 188]
  [ 94 124 183]]

 [[102 132 213]
  [ 98 128 209]
  [ 95 125 208]
  ...
  [109 140 209]
  [115 146 209]
  [101 133 192]]

 [[101 131 214]
  [ 98 128 211]
  [ 96 126 209]
  ...
  [ 83 116 185]
  [109 142 205]
  [ 82 117 173]]

 ...

 [[ 86 118 201]
  [ 88 120 203]
  [ 89 121 204]
  ...
  [168 162 163]
  [134 126 127]
  [ 68  60  61]]

 [[ 86 118 201]
  [ 87 119 202]
  [ 88 120 203]
  ...
  [ 74  68  69]
  [146 138 139]
  [175 167 168]]

 [[ 85 117 200]
  [ 86 118 201]
  [ 87 119 202]
  ...
  [  5   0   0]
  [ 15   7   8]
  [ 82  74  75]]]


### Crating a copy of a portion

In [7]:
img= cv2.imread('watch.jpg', 1)

roi= img[200:700, 250:900]
img[0:500,0:650]=roi

cv2.imshow('Copy Portion Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Image Arithematic

In [10]:
img1= cv2.imread('scatterplot2.jpg', 1)
img2= cv2.imread('jvyv1.png', 1)

#Resizing the image
img1= cv2.resize(img1, (600,600), interpolation= cv2.INTER_CUBIC)
img2= cv2.resize(img2, (600,600), interpolation= cv2.INTER_CUBIC)

add= img1+img2

cv2.imshow('Added Image',add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
#Using cv2.add() function
img1= cv2.imread('scatterplot2.jpg', 1)
img2= cv2.imread('jvyv1.png', 1)

#Resizing the image
img1= cv2.resize(img1, (600,600), interpolation= cv2.INTER_CUBIC)
img2= cv2.resize(img2, (600,600), interpolation= cv2.INTER_CUBIC)

add= cv2.add(img1, img2)

cv2.imshow('Added Image',add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#Using addWeighted() function
img1= cv2.imread('scatterplot2.jpg', 1)
img2= cv2.imread('jvyv1.png', 1)

#Resizing the image
img1= cv2.resize(img1, (600,600), interpolation= cv2.INTER_CUBIC)
img2= cv2.resize(img2, (600,600), interpolation= cv2.INTER_CUBIC)

add= cv2.addWeighted(img1, 0.6, img2, 0.4, 0)

cv2.imshow('Added Image',add)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Add an Image to Another Image 

In [18]:
img1= cv2.imread('jvyv1.png', 1)
img2= cv2.imread('python-logo.png', 1)

img1= cv2.resize(img1, (1224,1624), interpolation= cv2.INTER_CUBIC)

rows, columns, channel= img2.shape
roi= img1[0:rows,0:columns]

img2gray= cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

#thresholding the logo image
ret, mask= cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('Thresholded Image',mask)

mask_inv= cv2.bitwise_not(mask)
cv2.imshow('Mask INV Image',mask_inv)

img1_bg= cv2.bitwise_and(roi, roi, mask=mask_inv)
cv2.imshow('Image 1 Background',img1_bg)

img2_fg= cv2.bitwise_and(img2, img2, mask=mask)
cv2.imshow('Image 2 Foreground',img2_fg)

dst= cv2.add(img1_bg, img2_fg)
img1[0:rows,0:columns]= dst

cv2.imshow('Logo Image before adding', dst)
cv2.imshow('Added Image',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()